### ISSUE TITLE
Dataset construction link is broken

### ISSUE THREAD

**Issue by gabrevaya** [HennyJie/BrainGB#7]
First of all, thanks for such a great paper and package!

The link that is supposed to contain the instructions for creating our own dataset is broken:
[https://brainnet.us/instructions/](https://brainnet.us/instructions/)

If the fixing of that would take some considerable time, in the mean time could you please let me know the file format and structure that the dataset should have? I already have some fMRI functional connectivity matrices from another dataset and I'd like to test your codes to check the performance on classification.

**Comment by HennyJie** [comment]
Sure. Thanks for your interest for our work! I will upload an example dataset of the PPMI (which is public available upon approval) for your convenience later this week.

**Comment by gabrevaya** [comment]
Thanks!!

**Comment by SaqibMamoon** [comment]
@HennyJie  Have you uploaded the example dataset setting for PPMI, as I can't find here! Please guide

**Comment by LearningKeqi** [comment]
Thank you for your interest in this work! We understand the challenges faced by researchers in accessing certain datasets due to restrictions. To facilitate your experimentation with BrainGB, we provide the [Autism Brain Imaging Data Exchange (ABIDE) dataset](http://fcon_1000.projects.nitrc.org/indi/abide/abide_I.html), which is publicly accessible and does not require special access permissions. 

- [Download and Preprocess ABIDE dataset here](https://github.com/HennyJie/BrainGB/tree/master/examples/utils/get_abide)
