### ISSUE TITLE
Dataset Construction Link is still Broken! 

### ISSUE THREAD

**Issue by SaqibMamoon** [HennyJie/BrainGB#9]
Hi, Thank you sharing such a great project and insightful article and code. However, dataset reconstruction link is broken, and I can't find here. 

Also, Could you please elaborate what should be the shape the dataset before input like for ABIDE dataset.

`
def load_data_abide(abide_path):

    data = np.load(abide_path + '/abide.npy', allow_pickle=True).item()

    final_pearson = data["corr"]

    labels = data["label"]

    return final_pearson, labels
`

How did you construct the abide.npy file, like data shape and structure of it.     

Thanks!!

**Comment by LearningKeqi** [comment]
Thank you for your interest in this work! We understand the challenges faced by researchers in accessing certain datasets due to restrictions. To facilitate your experimentation with BrainGB, we provide the [Autism Brain Imaging Data Exchange (ABIDE) dataset](http://fcon_1000.projects.nitrc.org/indi/abide/abide_I.html), which is publicly accessible and does not require special access permissions. 

- [Download and Preprocess ABIDE dataset here](https://github.com/HennyJie/BrainGB/tree/master/examples/utils/get_abide)

After the download and preprocess steps, you should get `abide.npy` dataset, please place the dataset file "abide.npy"  in the `datasets` folder under the `examples` folder (Create the folder if it does not exist).
